Description: Aspan frontend pipeline (kappa)

Parameters:
  ProjectName:
    Type: String
  GitBranchName:
    Description: Environment name, same as GitHub branch name
    Type: String
  FullRepositoryId:
    Type: String
  PrincipalOrgID:
    Type: String

Resources:
  InfrastructureBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${AWS::StackName}-infra
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldObjects
            Status: Enabled
            ExpirationInDays: 30
          - Id: IntelligentTieringRule
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: INTELLIGENT_TIERING

  InfrastructureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InfrastructureBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: s3:*
            Effect: Allow
            Resource: !Sub ${InfrastructureBucket.Arn}/*
            Principal: "*"
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref PrincipalOrgID

  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: WebAppGitRepositoryConnection
      ProviderType: GitHub

  CodePipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WebAppCodePipelineExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codepipeline.amazonaws.com
      Path: /
      Policies:
        - PolicyName: !Sub ${ProjectName}-${GitBranchName}-CodePipelineExecutionRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:*
                  - s3:*
                  - iam:GetRole
                  - codestar-connections:UseConnection
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: "*"

  CodeBuildExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WebAppCodeBuildExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: AWS-CodeBuild-Service
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DeleteLogGroup
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub ${InfrastructureBucket.Arn}/*
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudformation.amazonaws.com
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource: "*"

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ProjectName}-${GitBranchName}-pipeline
      RoleArn: !GetAtt CodePipelineExecutionRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref InfrastructureBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeRepo
              Namespace: SourceCodeRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: SourceAsZip
              Configuration:
                BranchName: !Ref GitBranchName
                ConnectionArn: !Ref CodeStarConnection
                FullRepositoryId: !Ref FullRepositoryId
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceAsZip
              Configuration:
                ProjectName: !Ref CodeBuildProject
                EnvironmentVariables:
                  !Join [
                    "",
                    [
                      '[',
                      '{"name":"GIT_BRANCH","value":"#{SourceCodeRepo.BranchName}","type":"PLAINTEXT"}',
                      ',',
                      '{"name":"HOSTING_BUCKET","value":"',
                      !ImportValue WebsiteHostingBucketName,
                      '","type":"PLAINTEXT"}',
                      ',',
                      '{"name":"REACT_APP_CLOUDFRONT_URL","value":"',
                      !ImportValue CloudFrontDistributionUrl,
                      '","type":"PLAINTEXT"}',
                      ']',
                    ],
                  ]

  CodeStarNotification:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: !Sub ${AWS::StackName}-notify
      DetailType: BASIC
      Resource: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${GitBranchName}-pipeline
      EventTypeIds: 
        - codepipeline-pipeline-pipeline-execution-failed
        - codepipeline-pipeline-pipeline-execution-succeeded
      Targets: 
        - TargetType: SNS 
          TargetAddress: !Ref NotificationTopic

  NotificationTopic:
    Type: AWS::SNS::Topic

  NotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: 
        - !Ref NotificationTopic
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - SNS:GetTopicAttributes
              - SNS:SetTopicAttributes
              - SNS:AddPermission
              - SNS:RemovePermission
              - SNS:DeleteTopic
              - SNS:Subscribe
              - SNS:ListSubscriptionsByTopic
              - SNS:Publish
              - SNS:Receive
            Resource: !Ref NotificationTopic
            Condition:
              StringEquals:
                aws:SourceOwner: !Sub ${AWS::AccountId}
          - Effect: Allow
            Sid: AWSCodeStarNotifications_publish
            Principal:
              Service: codestar-notifications.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref NotificationTopic
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${ProjectName}-${GitBranchName}
      ServiceRole: !GetAtt CodeBuildExecutionRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: infrastructure/buildspec.yaml
